runners:
  - name: "gpu-runner"
    cloud: "gcp"
    gpu: "nvidia-tesla-t4"
    instance_type: "n1-standard-1"
    machine_image: "ubuntu-2004-focal-v20221018"
    preemptible: false
    labels:
      - "cirun-gpu-runner"
