[package]
name = "axion"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axion-macro = { path = "../macro" }

[dev-dependencies]
criterion = "0.5.1"

[features]
default=["math"]
math=[]
simd=[]
